config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  resources :posts do
	resources :comments
end
  resources :employees
  resources :holidays
  resources :leaves
  devise_for :users

 root 'pages#home'

  get "staff/employees" => "pages#staff", as: :staff
	
  get "leave/holidays" => "pages#leave", as: :leave

  get "blog/posts" => "pages#blog", as: :blog

  get "login" => "login", as: :login

 

end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
	def self.search(search)
		if search
			where(["name LIKE ?","%#{search}%"])
		else
		   all
		end
	end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]

  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.search(params[:search])
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: 'Holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holiday_params
      params.require(:holiday).permit(:name, :department, :type, :startDate, :endDate, :phone, :details)
    end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<%= form_for(@holiday) do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :startDate %><br>
    <%= f.number_field :startDate %>
  </div>
  <div class="field">
    <%= f.label :endDate %><br>
    <%= f.number_field :endDate %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
<h1>Editing Holiday</h1>

<%= render 'form' %>

<%= link_to 'Show', @holiday %> |
<%= link_to 'Back', holidays_path %>

app/views/holidays/index.html.erb
<p id="notice"><%= notice %></p>



<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>HR Department</h1>
        <p>Student no: x13121529</p>
        <p>Student Name: Jennifer Mwangi</p>
	<p class="text-center"><a href="http://github.com/jenniferwangui" target="_blank" class="btn btn-primary btn-lg">Show me the code</a></p>
		</div>
      </div>
    </div>


	<div class="alt1">
	<div class="container">
	<div class="row">
	<div class="col-md-12">
<h1 class="text-center">Listing Holidays</h1>

	<h4>enter your name</h4>
	<%= form_tag holidays_path, :method => 'get' do %>
	  <%= text_field_tag :search, params[:search] %>
	  <%= submit_tag "search" %>
	<% end %>
<br />
<table>
  <thead>
    <tr>
      <th>Name</th>
	<br />
      <th>Department</th>
      <th>Type</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Phone</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><%= holiday.name %></td>
        <td><%= holiday.department %></td>
        <td><%= holiday.type %></td>
        <td><%= holiday.startDate %></td>
        <td><%= holiday.endDate %></td>
        <td><%= holiday.phone %></td>
        <td><%= holiday.details %></td>
        <td><%= link_to 'Show', holiday %></td>
        <td><%= link_to 'Edit', edit_holiday_path(holiday) %></td>
        <td><%= link_to 'Destroy', holiday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Holiday', new_holiday_path %>
<br >
<h5>FIELD TYPE: there is a problem with type field i donot know what happen its giving an error if you enter a word or
 numbers, the best way is to leave it blank not to interfere with the rest of the fields which is working well.
 I didn't want to replace the whole scaffold since it will intefere with the search button. Sorry for that. </h5>

</div>
</div>
</div>
</div>

app/views/holidays/new.html.erb
<h1>New Holiday</h1>

<%= render 'form' %>

<%= link_to 'Back', holidays_path %>

app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @holiday.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @holiday.department %>
</p>

<p>
  <strong>Type:</strong>
  <%= @holiday.type %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @holiday.startDate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @holiday.endDate %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @holiday.phone %>
</p>

<p>
  <strong>Details:</strong>
  <%= @holiday.details %>
</p>

<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', holidays_path %>