config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  resources :posts do
	resources :comments
end
  resources :employees
  resources :holidays
  resources :leaves
  devise_for :users

 root 'pages#home'

  get "staff/employees" => "pages#staff", as: :staff
	
  get "leave/holidays" => "pages#leave", as: :leave

  get "blog/posts" => "pages#blog", as: :blog

  get "login" => "login", as: :login

 

end

app/models/leave.rb
class Leave < ActiveRecord::Base
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
  before_action :set_leafe, only: [:show, :edit, :update, :destroy]

  # GET /leaves
  # GET /leaves.json
  def index
    @leaves = Leave.all
  end

  # GET /leaves/1
  # GET /leaves/1.json
  def show
  end

  # GET /leaves/new
  def new
    @leafe = Leave.new
  end

  # GET /leaves/1/edit
  def edit
  end

  # POST /leaves
  # POST /leaves.json
  def create
    @leafe = Leave.new(leafe_params)

    respond_to do |format|
      if @leafe.save
        format.html { redirect_to @leafe, notice: 'Leave was successfully created.' }
        format.json { render :show, status: :created, location: @leafe }
      else
        format.html { render :new }
        format.json { render json: @leafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaves/1
  # PATCH/PUT /leaves/1.json
  def update
    respond_to do |format|
      if @leafe.update(leafe_params)
        format.html { redirect_to @leafe, notice: 'Leave was successfully updated.' }
        format.json { render :show, status: :ok, location: @leafe }
      else
        format.html { render :edit }
        format.json { render json: @leafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaves/1
  # DELETE /leaves/1.json
  def destroy
    @leafe.destroy
    respond_to do |format|
      format.html { redirect_to leaves_url, notice: 'Leave was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leafe
      @leafe = Leave.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leafe_params
      params.require(:leafe).permit(:name, :department, :type, :start_date, :end_date, :phone)
    end
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/leaves/_form.html.erb
<%= form_for(@leafe) do |f| %>
  <% if @leafe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leafe.errors.count, "error") %> prohibited this leafe from being saved:</h2>

      <ul>
      <% @leafe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.number_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.number_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leaves/edit.html.erb
<h1>Editing Leafe</h1>

<%= render 'form' %>

<%= link_to 'Show', @leafe %> |
<%= link_to 'Back', leaves_path %>

app/views/leaves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leaves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th>Type</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leaves.each do |leafe| %>
      <tr>
        <td><%= leafe.name %></td>
        <td><%= leafe.department %></td>
        <td><%= leafe.type %></td>
        <td><%= leafe.start_date %></td>
        <td><%= leafe.end_date %></td>
        <td><%= leafe.phone %></td>
        <td><%= link_to 'Show', leafe %></td>
        <td><%= link_to 'Edit', edit_leafe_path(leafe) %></td>
        <td><%= link_to 'Destroy', leafe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leave', new_leafe_path %>

app/views/leaves/new.html.erb
<h1>New Leafe</h1>

<%= render 'form' %>

<%= link_to 'Back', leaves_path %>

app/views/leaves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @leafe.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @leafe.department %>
</p>

<p>
  <strong>Type:</strong>
  <%= @leafe.type %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @leafe.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @leafe.end_date %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @leafe.phone %>
</p>

<%= link_to 'Edit', edit_leafe_path(@leafe) %> |
<%= link_to 'Back', leaves_path %>